[workspace]

members = [
    "crates/bottomless",
    "crates/bottomless-cli",
    "crates/sqlc",
    "crates/sqld",
    "crates/sqld-libsql-bindings",
    "testing/end-to-end",
]

[patch.crates-io]
uuid = { git = "https://github.com/psarna/uuid", branch = "stable_v7" }
