[package]
name = "edge"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
bincode = "1.3.3"
clap = { version = "4.0.23", features = [ "derive" ] }
crossbeam = "0.8.2"
env_logger = "0.9.3"
log = "0.4.17"
message-io = "0.14.6"
rayon = "1.5.3"
rstest = "0.15.0"
rustyline = "10.0.0"
serde = "1.0.147"
sqlite = "0.30.1"
sqlparser = "0.27.0"
