[workspace]

members = [
    "bottomless",
    "bottomless-cli",
    "libsql-client",
    "sqlc",
    "sqld",
]

[patch.crates-io]
uuid = { git = "https://github.com/psarna/uuid", branch = "stable_v7" }
