version: "3.9"
services:
  writer:
    build: .
    environment:
      - IKU_TURSO_NODE=primary
    ports:
      - "6000:5000"
  reader:
    build: .
    environment:
      - RUST_LOG=server=trace
      - IKU_TURSO_NODE=replica
      - IKU_TURSO_PRIMARY_URL="http://writer:5001"
    depends_on:
      - writer
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - reader
    ports:
      - "6001:6001"

