[package]
name = "libsql-client"
version = "0.4.1"
edition = "2021"
license = "Apache-2.0"
description = "HTTP-based client for libSQL and sqld"
keywords = ["libsql", "sqld", "database", "driver", "http"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.3.1"
base64 = "0.21.0"
num-traits = "0.2.15"
serde_json = "1.0.91"
worker = { version = "0.0.12", optional = true }
anyhow = "1.0.69"
async-trait = "0.1.64"
reqwest = { version = "0.11.14", optional = true }

[features]
workers_backend = ["worker"]
reqwest_backend = ["reqwest"]

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
libsql-client = { path = ".", features = ["reqwest_backend"] }
rand = "0.8.5"

[[example]]
name = "select"
path = "examples/select.rs"
