[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.58"
byteorder = "1.4.3"
bytes = "1.2.1"
clap = { version = "4.0.23", features = [ "derive" ] }
crossbeam = "0.8.2"
foundationdb = { version = "0.7.0", features = ["embedded-fdb-include"], optional = true }
futures = "0.3.25"
hex = "0.4.3"
parking_lot = "0.12.1"
pgwire = "0.5.0"
pin-project-lite = "0.2.9"
postgres-protocol = "0.6.4"
rusqlite = { version = "0.28.0", features = [ "buildtime_bindgen", "column_decltype" ] }
serde = { version = "1.0.149", features = ["derive"] }
smallvec = "1.10.0"
sqlparser = "0.27.0"
tokio = { version = "1.21.2", features = ["full"] }
tokio-tungstenite = "0.17.2"
tokio-util = "0.7.4"
tower = { version = "0.4.13", features = ["make"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

[dev-dependencies]
proptest = "1.0.0"
rand = "0.8.5"

[features]
fdb = ["foundationdb"]
