[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
bincode = "1.3.3"
bytes = "1.2.1"
clap = { version = "4.0.23", features = [ "derive" ] }
crossbeam = "0.8.2"
env_logger = "0.9.3"
futures = "0.3.25"
log = "0.4.17"
parking_lot = "0.12.1"
rayon = "1.5.3"
rstest = "0.15.0"
rustyline-async = "0.3.0"
serde = { version = "1.0.147", features = ["derive"]}
smallvec = "1.10.0"
sqlite = "0.30.1"
sqlparser = "0.27.0"
tokio = { version = "1.21.2", features = ["full"] }

[dev-dependencies]
proptest = "1.0.0"
rand = "0.8.5"
