name: Bottomless store and restore

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      minio:
        image: fclairamb/minio-github-actions
        ports:
          - 9000:9000
    env:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_DEFAULT_REGION: eu-central-2
      LIBSQL_BOTTOMLESS_BUCKET: bottomless
      LIBSQL_BOTTOMLESS_ENDPOINT: http://localhost:9000
      RUST_LOG: info,bottomless=trace
    steps:
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: set up LIBSQL_DIR
      run: |
        echo "LIBSQL_DIR=$GITHUB_WORKSPACE/libsql" >> $GITHUB_ENV

    - name: drop sqlite3
      run: sudo apt remove sqlite3 libsqlite3-dev

    - name: Checkout libsql
      uses: actions/checkout@v3
      with:
        repository: libsql/libsql
        path: ./libsql

    - name: Build libsql
      working-directory: ./libsql/
      run: ./configure && make libsql sqlite3.h sqlite3ext.h

    - name: Run smoke test
      working-directory: ./bottomless
      run: make test

    - name: Run restore test
      working-directory: ./bottomless/test
      run: ../../libsql/libsql < restore_test.sql

    - name: Remove the database
      working-directory: ./bottomless/test
      run: rm -f test/test.db

    - name: Run restore test again
      working-directory: ./bottomless/test
      run: ../../libsql/libsql < restore_test.sql

    - name: Make offline changes to the database
      working-directory: ./bottomless/test
      run: ../../libsql/libsql test.db <<< "insert into test values (997);"

    - name: Run restore test yet again
      working-directory: ./bottomless/test
      run: ../../libsql/libsql < restore_test.sql

    - name: List generations with CLI
      run: cargo run -p bottomless-cli -- -e http://localhost:9000 -d test.db ls -v

    - name: Restore the database with CLI
      run: cargo run -p bottomless-cli -- -e http://localhost:9000 -d test.db restore

    - name: Verify the restored database
      working-directory: ./bottomless/test
      run: ../../libsql/libsql test.db <<< "SELECT * FROM test;"
