name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install deps
      run: sudo apt-get update -y && sudo apt-get install -y bundler
    - uses: actions/checkout@v3
    - name: Check format
      run: cargo fmt --check
    - name: Checkout libsql
      run: ( git submodule update --init --force --recursive )
    - name: Clippy
      run: cargo clippy
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run functional tests
      run: make test
